### ISSUE TITLE
Upstream

### ISSUE THREAD

**Issue by owenthewizard** [LoganDark/imgref-iter#1]
Have you considered merging this into `imgref`? I would think they'd be interested.

**Comment by LoganDark** [comment]
I don't think they'd be interested in piles of copy-pasted unsafe code that manipulates raw pointers without any tests. I had miri testing in the past, but this library has so many iterators now that I decided to exclude the tests from the repository because they no longer covered the whole lib.

I haven't gone through the effort of deduplicating all the iterator code using macros yet, so right now it's just a copy-paste error waiting to happen. I wish I could say I can guarantee it hasn't happened, but I caught one during development so I'm really not sure.

Plus, this crate is centered around `Img<*[T]>` but [`imgref` does not even support `Img<*[T]>`](https://github.com/kornelski/imgref/issues/17#issuecomment-1158730806), it was just an accident that happened as a result of using generics. I'm not sure if they'd want to condone this sort of thing.

This library offers safe iterators, but it is *centered* around very powerful *unsafe* iterators, to the point where all of the safe iterators are built on top of them. This is niche at best, and my usage of it is even more niche and unsafe, to the point of being downright scary.

My opinion may change if @kornelski decides to come on over and offer their opinion (and it turns out favorable), but in short: I don't think `imgref` would want this, and I don't think `imgref` would appreciate my implementation of it. If it's ever going to be proposed to upstream, the unsafe iterators (and implementations of them) would probably have to go, which means I wouldn't find them useful anymore.

I think offering this as a third-party crate is the best solution right now. Would take quite a lot to change my mind.

Closing this as not planned unless a miracle happens.

**Comment by kornelski** [comment]
I would like to support mutable column slices, but unfortunately it's not sound in `imgref`. I've made it have a concept of "padding" (for working with block-based video formats), and this exposes too much of the underlying buffer. I'll probably make imgref 2.0 someday with a properly private buffer.

**Comment by LoganDark** [comment]
> mutable column slices

It is impossible to offer a column as a slice unless stride is 1. Slices must be contiguous.

> this exposes too much of the underlying buffer. I'll probably make imgref 2.0 someday with a properly private buffer.

Do you think `imgref-iter`'s use of `Img` is unintended/unsupported? It doesn't access the private fields, but it does make a lot of assumptions.

In other words, would `imgref-iter` be possible on top of a future `imgref` 2.0?

**Comment by kornelski** [comment]
I mean logical column slices using `*mut T`-based abstraction, not the `&mut [T]` type slices. 

It's safe to make assumptions about data layout of `imgref`. It's a buffer with rows separated by stride, and a gotcha that the last row may be equal to width, but not stride.

**Comment by LoganDark** [comment]
> I mean logical column slices using `*mut T`-based abstraction, not the `&mut [T]` type slices.

`imgref-iter` offers column iterators over `&T` and `&mut T`. So I'd say that this fills the niche good enough. :)

Maybe I'll implement indexing and slicing operations for the iterators just to make them more useful.

> and a gotcha that the last row may be equal to width, but not stride.

`imgref-iter` handles this correctly. :)

It's guaranteed not to even `offset` into the "trailing stride".
