### ISSUE TITLE
`Img` slice length is not verified

### ISSUE THREAD

**Issue by RealKC** [LoganDark/imgref-iter#3]
These lines

https://github.com/LoganDark/stackblur-iter/blob/53be4ee685f2bc1fbbb79b9ab02ee6679de85694/src/lib.rs#L82-L83

call into the `rows` and `cols` methods of [ImgIterPtrMut](https://docs.rs/imgref-iter/0.3.1/imgref_iter/traits/trait.ImgIterPtrMut.html). Let's take `iter_rows_ptr_mut`, as it shouldn't matter which of the two paths we take I think. That ones call into [this implementation](https://github.com/LoganDark/imgref-iter/blob/2de398cd26aab08e9a6f302d7e426ceb6b74478a/src/traits.rs#L554-L557) which calls into [`IterWindowsPtrMut::rows_ptr`](https://github.com/LoganDark/imgref-iter/blob/2de398cd26aab08e9a6f302d7e426ceb6b74478a/src/iter/windows/ptr.rs#L221-L226) which assumes that the provided dimensions are correct, however a user can provide wrong dimensions accidentally, which will lead to memory corruption. Here's a test that segfaults on my machine

```rs
#[test]
fn blur_argb_with_bogus_dimensions() {
    let mut img: ImgRefMut<u32> = ImgRefMut::new(&mut [], 1000, 1000);

    stackblur_iter::blur_argb(&mut img, 12);
}
```

as `blur_argb` only calls safe functions, the only option is that `blur` - which calls unsafe functions - has to be unsound

**Comment by LoganDark** [comment]
Moved this to `imgref-iter` because the safe `iter_rows`/`iter_cols` methods should validate that the passed image reference has correct dimensions. Thanks for the report!

(Though I do call ptr functions before that, so `stackblur-iter` should *also* validate - so this is an issue with both of them.)

**Comment by LoganDark** [comment]
So this is indeed a soundness issue in `imgref-iter`. In the `IterWindowsPtr::new` function, you can see it's doing *a* check:

https://github.com/LoganDark/imgref-iter/blob/2de398cd26aab08e9a6f302d7e426ceb6b74478a/src/iter/windows/ptr.rs#L47

There are two layers to this:

- This actually isn't even the correct check to use; this is the check for iterating over one row or column, but the windows iterators hand out iterators over multiple rows or columns. This needs a new, unique check.
- Windows constructor functions (rows/cols) use `new_unchecked` instead of `new`, eliding the checks anyway. This means they either need to switch to `new` if it can be checked, or add their own checks.

**Comment by LoganDark** [comment]
Please verify if the [`is_slice_enough` branch](https://github.com/LoganDark/imgref-iter/tree/is_slice_enough) that I just pushed fixes your issue :)

**Comment by RealKC** [comment]
I ran the test I included in the original comment and that (correctly) panics now, which does indeed fix the issue

**Comment by LoganDark** [comment]
Awesome! It also correctly *does not* panic in my real test app. New `imgref-iter` has been published; any app using `stackblur-iter` should pick up the fix automatically by running `cargo update`.

Closing this as resolved :) thanks for the report!
